# Generated by Django 5.2.7 on 2025-10-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='channel_id',
            field=models.CharField(default='temp-channel-id', help_text='請輸入此商家的 LINE Channel ID，它將作為唯一的識別碼。', max_length=150, unique=True, verbose_name='LINE Channel ID'),
            preserve_default=False,
        ),
    ]
