# Generated by Django 5.2.7 on 2025-11-26 03:07

import lut2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(choices=[('portrait', '直式'), ('landscape', '橫式')], default='portrait', max_length=10, verbose_name='方向')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lut2.models.upload_to, verbose_name='圖片檔案')),
                ('image_base64', models.TextField(blank=True, null=True, verbose_name='Base64 圖片資料')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='原始檔名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '上傳圖片',
                'verbose_name_plural': '上傳圖片',
                'ordering': ['-created_at'],
            },
        ),
    ]
