# Generated by Django 5.2.7 on 2025-12-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lut2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='image_base64',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='poem_author',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='詩詞作者'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='poem_content',
            field=models.TextField(blank=True, null=True, verbose_name='詩詞內容'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='poem_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='詩詞標題'),
        ),
    ]
